### ISSUE TITLE
Automatically generate access tokens

### ISSUE THREAD

**Issue by jakob** [fedoco/itc-reporter#10]
Apple has just sent out the following email:

> We’ve also updated Reporter to let you generate an access token with the new generateToken command. To use this new command, [download Reporter 2.2](https://help.apple.com/itc/appsreporterguide/?lang=eng#/apda86f89da5).
> 
> Find out how to [generate an access token](https://help.apple.com/itc/appsreporterguide/?lang=en#/apd2f1f1cfa3), and get details on automating downloads of your Sales and Trends reports and Financial reports in the [Reporter User Guide](https://help.apple.com/itc/appsreporterguide/?lang=eng#/itcbe21ac7db).

I think this is great news! Generating the token in iTunes Connect is really cumbersome. It would be really nice if we could add a command to automatically generate the token. 

The first step would be to reverse engineer what command iTunes Reporter sends to generates tokens.

**Comment by fedoco** [comment]
Yes, I'm already on it. The command for generating tokens is simply `generateToken`. In a first step, I'm going to add it as a new command line action along with `viewToken` and `deleteToken` to mirror **Reporter**'s capabilities.
In a second step, I think these even could be automated, including storing fresh access tokens in Keychain. Or would that mean too much "magic" going on?

**Comment by jakob** [comment]
I've also been thinking about this. For example, you could allow the user to provide both `-t` and `-p` arguments. If there is no token, or if the token is expired, itc-reporter would then automatically generate a token using the password from the keychain item `-p`, and then store the new token in item `-t`.

This would make it easier to use itc-reporter in automated scripts, since I never need to worry about manually refreshing the token.

**Comment by jakob** [comment]
(But we would need to wait 180 days before we could test if the logic that detects expired token errors works ....)

**Comment by fedoco** [comment]
I bet there is going to be the word "expired" in responses after 180 days, so we could just scan for that. And because `viewToken` returns a known string both for expired and non-existent tokens it's probably a safe approach to call it for confirmation before any automatic token creation. I guess a new parameter for dis/enabling automatic token management wouldn't hurt either.

Meanwhile, I've found that unfortunately it isn't as simple as throwing `generateToken` at iTC in order to make it spit out a new one. As you predicted I need to intercept *Reporter* to see how it's done but don't have my setup for doing so handy at the moment and will have to do it later. `viewToken` and `deleteToken` already work as one would expect.

**Comment by fedoco** [comment]
I think I now have also successfully implemented `generateToken` in d592333. Would you mind giving it a try before automating it?

Unfortunately I had to break backwards compatibility somewhat because the parameters `-t` and `-T` aren't required anymore for every single command. Consequently, I had to move them into subparsers and now ArgumentParser is rather picky about the correct order and expects them *after* a command like `getStatus` or `getSalesReport`.

**Comment by fedoco** [comment]
I have added the ability to update Keychain when generating a new token in 67ec9fb11e7d49da3f4e992e0ba1608a844bcb55.
